
  const {
      linkTypeMap,
      createClient: createClientOriginal,
      generateGraphqlOperation,
      assertSameVersion,
  } = require('@gqlts/runtime')
  var typeMap = linkTypeMap(require('./types.cjs'))

  var version = '3.2.19-beta.149'
  assertSameVersion(version)

  module.exports.version = version

  module.exports.createClient = 
function(options) {
    options = options || {}
    var optionsCopy = {
      url: "https://suplab.myshopify.com/api/2023-07/graphql.json",
      queryRoot: typeMap.Query,
      mutationRoot: typeMap.Mutation,
      subscriptionRoot: typeMap.Subscription,
    }
    for (var name in options) {
      optionsCopy[name] = options[name];
    }
    return createClientOriginal(optionsCopy)
}

  module.exports.enumArticleSortKeys = {
  ID: 'ID',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE',
  BLOG_TITLE: 'BLOG_TITLE',
  AUTHOR: 'AUTHOR',
  UPDATED_AT: 'UPDATED_AT',
  PUBLISHED_AT: 'PUBLISHED_AT'
}

module.exports.enumBlogSortKeys = {
  ID: 'ID',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE',
  HANDLE: 'HANDLE'
}

module.exports.enumCardBrand = {
  VISA: 'VISA',
  MASTERCARD: 'MASTERCARD',
  DISCOVER: 'DISCOVER',
  AMERICAN_EXPRESS: 'AMERICAN_EXPRESS',
  DINERS_CLUB: 'DINERS_CLUB',
  JCB: 'JCB'
}

module.exports.enumCartCardSource = {
  SAVED_CREDIT_CARD: 'SAVED_CREDIT_CARD'
}

module.exports.enumCartErrorCode = {
  INVALID: 'INVALID',
  LESS_THAN: 'LESS_THAN',
  INVALID_MERCHANDISE_LINE: 'INVALID_MERCHANDISE_LINE',
  MISSING_DISCOUNT_CODE: 'MISSING_DISCOUNT_CODE',
  MISSING_NOTE: 'MISSING_NOTE',
  INVALID_DELIVERY_GROUP: 'INVALID_DELIVERY_GROUP',
  INVALID_DELIVERY_OPTION: 'INVALID_DELIVERY_OPTION',
  INVALID_PAYMENT: 'INVALID_PAYMENT',
  INVALID_PAYMENT_EMPTY_CART: 'INVALID_PAYMENT_EMPTY_CART',
  PAYMENT_METHOD_NOT_SUPPORTED: 'PAYMENT_METHOD_NOT_SUPPORTED',
  INVALID_METAFIELDS: 'INVALID_METAFIELDS'
}

module.exports.enumCheckoutErrorCode = {
  BLANK: 'BLANK',
  INVALID: 'INVALID',
  TOO_LONG: 'TOO_LONG',
  PRESENT: 'PRESENT',
  LESS_THAN: 'LESS_THAN',
  LESS_THAN_OR_EQUAL_TO: 'LESS_THAN_OR_EQUAL_TO',
  GREATER_THAN_OR_EQUAL_TO: 'GREATER_THAN_OR_EQUAL_TO',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  LOCKED: 'LOCKED',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  BAD_DOMAIN: 'BAD_DOMAIN',
  INVALID_FOR_COUNTRY: 'INVALID_FOR_COUNTRY',
  INVALID_FOR_COUNTRY_AND_PROVINCE: 'INVALID_FOR_COUNTRY_AND_PROVINCE',
  INVALID_STATE_IN_COUNTRY: 'INVALID_STATE_IN_COUNTRY',
  INVALID_PROVINCE_IN_COUNTRY: 'INVALID_PROVINCE_IN_COUNTRY',
  INVALID_REGION_IN_COUNTRY: 'INVALID_REGION_IN_COUNTRY',
  SHIPPING_RATE_EXPIRED: 'SHIPPING_RATE_EXPIRED',
  GIFT_CARD_UNUSABLE: 'GIFT_CARD_UNUSABLE',
  GIFT_CARD_DISABLED: 'GIFT_CARD_DISABLED',
  GIFT_CARD_CODE_INVALID: 'GIFT_CARD_CODE_INVALID',
  GIFT_CARD_ALREADY_APPLIED: 'GIFT_CARD_ALREADY_APPLIED',
  GIFT_CARD_CURRENCY_MISMATCH: 'GIFT_CARD_CURRENCY_MISMATCH',
  GIFT_CARD_EXPIRED: 'GIFT_CARD_EXPIRED',
  GIFT_CARD_DEPLETED: 'GIFT_CARD_DEPLETED',
  GIFT_CARD_NOT_FOUND: 'GIFT_CARD_NOT_FOUND',
  CART_DOES_NOT_MEET_DISCOUNT_REQUIREMENTS_NOTICE: 'CART_DOES_NOT_MEET_DISCOUNT_REQUIREMENTS_NOTICE',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_DISABLED: 'DISCOUNT_DISABLED',
  DISCOUNT_LIMIT_REACHED: 'DISCOUNT_LIMIT_REACHED',
  HIGHER_VALUE_DISCOUNT_APPLIED: 'HIGHER_VALUE_DISCOUNT_APPLIED',
  MAXIMUM_DISCOUNT_CODE_LIMIT_REACHED: 'MAXIMUM_DISCOUNT_CODE_LIMIT_REACHED',
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  CUSTOMER_ALREADY_USED_ONCE_PER_CUSTOMER_DISCOUNT_NOTICE: 'CUSTOMER_ALREADY_USED_ONCE_PER_CUSTOMER_DISCOUNT_NOTICE',
  DISCOUNT_CODE_APPLICATION_FAILED: 'DISCOUNT_CODE_APPLICATION_FAILED',
  EMPTY: 'EMPTY',
  NOT_ENOUGH_IN_STOCK: 'NOT_ENOUGH_IN_STOCK',
  MISSING_PAYMENT_INPUT: 'MISSING_PAYMENT_INPUT',
  TOTAL_PRICE_MISMATCH: 'TOTAL_PRICE_MISMATCH',
  LINE_ITEM_NOT_FOUND: 'LINE_ITEM_NOT_FOUND',
  UNABLE_TO_APPLY: 'UNABLE_TO_APPLY',
  DISCOUNT_ALREADY_APPLIED: 'DISCOUNT_ALREADY_APPLIED',
  THROTTLED_DURING_CHECKOUT: 'THROTTLED_DURING_CHECKOUT',
  EXPIRED_QUEUE_TOKEN: 'EXPIRED_QUEUE_TOKEN',
  INVALID_QUEUE_TOKEN: 'INVALID_QUEUE_TOKEN',
  INVALID_COUNTRY_AND_CURRENCY: 'INVALID_COUNTRY_AND_CURRENCY',
  PRODUCT_NOT_AVAILABLE: 'PRODUCT_NOT_AVAILABLE'
}

module.exports.enumCollectionSortKeys = {
  ID: 'ID',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE',
  UPDATED_AT: 'UPDATED_AT'
}

module.exports.enumCompletionErrorCode = {
  ERROR: 'ERROR',
  INVENTORY_RESERVATION_ERROR: 'INVENTORY_RESERVATION_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  PAYMENT_TRANSIENT_ERROR: 'PAYMENT_TRANSIENT_ERROR',
  PAYMENT_AMOUNT_TOO_SMALL: 'PAYMENT_AMOUNT_TOO_SMALL',
  PAYMENT_GATEWAY_NOT_ENABLED_ERROR: 'PAYMENT_GATEWAY_NOT_ENABLED_ERROR',
  PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT_INSUFFICIENT_FUNDS',
  PAYMENT_INVALID_PAYMENT_METHOD: 'PAYMENT_INVALID_PAYMENT_METHOD',
  PAYMENT_INVALID_CURRENCY: 'PAYMENT_INVALID_CURRENCY',
  PAYMENT_INVALID_CREDIT_CARD: 'PAYMENT_INVALID_CREDIT_CARD',
  PAYMENT_INVALID_BILLING_ADDRESS: 'PAYMENT_INVALID_BILLING_ADDRESS',
  PAYMENT_CARD_DECLINED: 'PAYMENT_CARD_DECLINED',
  PAYMENT_CALL_ISSUER: 'PAYMENT_CALL_ISSUER'
}

module.exports.enumCountryCode = {
  AF: 'AF',
  AX: 'AX',
  AL: 'AL',
  DZ: 'DZ',
  AD: 'AD',
  AO: 'AO',
  AI: 'AI',
  AG: 'AG',
  AR: 'AR',
  AM: 'AM',
  AW: 'AW',
  AC: 'AC',
  AU: 'AU',
  AT: 'AT',
  AZ: 'AZ',
  BS: 'BS',
  BH: 'BH',
  BD: 'BD',
  BB: 'BB',
  BY: 'BY',
  BE: 'BE',
  BZ: 'BZ',
  BJ: 'BJ',
  BM: 'BM',
  BT: 'BT',
  BO: 'BO',
  BA: 'BA',
  BW: 'BW',
  BV: 'BV',
  BR: 'BR',
  IO: 'IO',
  BN: 'BN',
  BG: 'BG',
  BF: 'BF',
  BI: 'BI',
  KH: 'KH',
  CA: 'CA',
  CV: 'CV',
  BQ: 'BQ',
  KY: 'KY',
  CF: 'CF',
  TD: 'TD',
  CL: 'CL',
  CN: 'CN',
  CX: 'CX',
  CC: 'CC',
  CO: 'CO',
  KM: 'KM',
  CG: 'CG',
  CD: 'CD',
  CK: 'CK',
  CR: 'CR',
  HR: 'HR',
  CU: 'CU',
  CW: 'CW',
  CY: 'CY',
  CZ: 'CZ',
  CI: 'CI',
  DK: 'DK',
  DJ: 'DJ',
  DM: 'DM',
  DO: 'DO',
  EC: 'EC',
  EG: 'EG',
  SV: 'SV',
  GQ: 'GQ',
  ER: 'ER',
  EE: 'EE',
  SZ: 'SZ',
  ET: 'ET',
  FK: 'FK',
  FO: 'FO',
  FJ: 'FJ',
  FI: 'FI',
  FR: 'FR',
  GF: 'GF',
  PF: 'PF',
  TF: 'TF',
  GA: 'GA',
  GM: 'GM',
  GE: 'GE',
  DE: 'DE',
  GH: 'GH',
  GI: 'GI',
  GR: 'GR',
  GL: 'GL',
  GD: 'GD',
  GP: 'GP',
  GT: 'GT',
  GG: 'GG',
  GN: 'GN',
  GW: 'GW',
  GY: 'GY',
  HT: 'HT',
  HM: 'HM',
  VA: 'VA',
  HN: 'HN',
  HK: 'HK',
  HU: 'HU',
  IS: 'IS',
  IN: 'IN',
  ID: 'ID',
  IR: 'IR',
  IQ: 'IQ',
  IE: 'IE',
  IM: 'IM',
  IL: 'IL',
  IT: 'IT',
  JM: 'JM',
  JP: 'JP',
  JE: 'JE',
  JO: 'JO',
  KZ: 'KZ',
  KE: 'KE',
  KI: 'KI',
  KP: 'KP',
  XK: 'XK',
  KW: 'KW',
  KG: 'KG',
  LA: 'LA',
  LV: 'LV',
  LB: 'LB',
  LS: 'LS',
  LR: 'LR',
  LY: 'LY',
  LI: 'LI',
  LT: 'LT',
  LU: 'LU',
  MO: 'MO',
  MG: 'MG',
  MW: 'MW',
  MY: 'MY',
  MV: 'MV',
  ML: 'ML',
  MT: 'MT',
  MQ: 'MQ',
  MR: 'MR',
  MU: 'MU',
  YT: 'YT',
  MX: 'MX',
  MD: 'MD',
  MC: 'MC',
  MN: 'MN',
  ME: 'ME',
  MS: 'MS',
  MA: 'MA',
  MZ: 'MZ',
  MM: 'MM',
  NA: 'NA',
  NR: 'NR',
  NP: 'NP',
  NL: 'NL',
  AN: 'AN',
  NC: 'NC',
  NZ: 'NZ',
  NI: 'NI',
  NE: 'NE',
  NG: 'NG',
  NU: 'NU',
  NF: 'NF',
  MK: 'MK',
  NO: 'NO',
  OM: 'OM',
  PK: 'PK',
  PS: 'PS',
  PA: 'PA',
  PG: 'PG',
  PY: 'PY',
  PE: 'PE',
  PH: 'PH',
  PN: 'PN',
  PL: 'PL',
  PT: 'PT',
  QA: 'QA',
  CM: 'CM',
  RE: 'RE',
  RO: 'RO',
  RU: 'RU',
  RW: 'RW',
  BL: 'BL',
  SH: 'SH',
  KN: 'KN',
  LC: 'LC',
  MF: 'MF',
  PM: 'PM',
  WS: 'WS',
  SM: 'SM',
  ST: 'ST',
  SA: 'SA',
  SN: 'SN',
  RS: 'RS',
  SC: 'SC',
  SL: 'SL',
  SG: 'SG',
  SX: 'SX',
  SK: 'SK',
  SI: 'SI',
  SB: 'SB',
  SO: 'SO',
  ZA: 'ZA',
  GS: 'GS',
  KR: 'KR',
  SS: 'SS',
  ES: 'ES',
  LK: 'LK',
  VC: 'VC',
  SD: 'SD',
  SR: 'SR',
  SJ: 'SJ',
  SE: 'SE',
  CH: 'CH',
  SY: 'SY',
  TW: 'TW',
  TJ: 'TJ',
  TZ: 'TZ',
  TH: 'TH',
  TL: 'TL',
  TG: 'TG',
  TK: 'TK',
  TO: 'TO',
  TT: 'TT',
  TA: 'TA',
  TN: 'TN',
  TR: 'TR',
  TM: 'TM',
  TC: 'TC',
  TV: 'TV',
  UG: 'UG',
  UA: 'UA',
  AE: 'AE',
  GB: 'GB',
  US: 'US',
  UM: 'UM',
  UY: 'UY',
  UZ: 'UZ',
  VU: 'VU',
  VE: 'VE',
  VN: 'VN',
  VG: 'VG',
  WF: 'WF',
  EH: 'EH',
  YE: 'YE',
  ZM: 'ZM',
  ZW: 'ZW',
  ZZ: 'ZZ'
}

module.exports.enumCropRegion = {
  CENTER: 'CENTER',
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT'
}

module.exports.enumCurrencyCode = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  CAD: 'CAD',
  AFN: 'AFN',
  ALL: 'ALL',
  DZD: 'DZD',
  AOA: 'AOA',
  ARS: 'ARS',
  AMD: 'AMD',
  AWG: 'AWG',
  AUD: 'AUD',
  BBD: 'BBD',
  AZN: 'AZN',
  BDT: 'BDT',
  BSD: 'BSD',
  BHD: 'BHD',
  BIF: 'BIF',
  BZD: 'BZD',
  BMD: 'BMD',
  BTN: 'BTN',
  BAM: 'BAM',
  BRL: 'BRL',
  BOB: 'BOB',
  BWP: 'BWP',
  BND: 'BND',
  BGN: 'BGN',
  MMK: 'MMK',
  KHR: 'KHR',
  CVE: 'CVE',
  KYD: 'KYD',
  XAF: 'XAF',
  CLP: 'CLP',
  CNY: 'CNY',
  COP: 'COP',
  KMF: 'KMF',
  CDF: 'CDF',
  CRC: 'CRC',
  HRK: 'HRK',
  CZK: 'CZK',
  DKK: 'DKK',
  DOP: 'DOP',
  XCD: 'XCD',
  EGP: 'EGP',
  ETB: 'ETB',
  XPF: 'XPF',
  FJD: 'FJD',
  GMD: 'GMD',
  GHS: 'GHS',
  GTQ: 'GTQ',
  GYD: 'GYD',
  GEL: 'GEL',
  HTG: 'HTG',
  HNL: 'HNL',
  HKD: 'HKD',
  HUF: 'HUF',
  ISK: 'ISK',
  INR: 'INR',
  IDR: 'IDR',
  ILS: 'ILS',
  IQD: 'IQD',
  JMD: 'JMD',
  JPY: 'JPY',
  JEP: 'JEP',
  JOD: 'JOD',
  KZT: 'KZT',
  KES: 'KES',
  KWD: 'KWD',
  KGS: 'KGS',
  LAK: 'LAK',
  LVL: 'LVL',
  LBP: 'LBP',
  LSL: 'LSL',
  LRD: 'LRD',
  LTL: 'LTL',
  MGA: 'MGA',
  MKD: 'MKD',
  MOP: 'MOP',
  MWK: 'MWK',
  MVR: 'MVR',
  MXN: 'MXN',
  MYR: 'MYR',
  MUR: 'MUR',
  MDL: 'MDL',
  MAD: 'MAD',
  MNT: 'MNT',
  MZN: 'MZN',
  NAD: 'NAD',
  NPR: 'NPR',
  ANG: 'ANG',
  NZD: 'NZD',
  NIO: 'NIO',
  NGN: 'NGN',
  NOK: 'NOK',
  OMR: 'OMR',
  PAB: 'PAB',
  PKR: 'PKR',
  PGK: 'PGK',
  PYG: 'PYG',
  PEN: 'PEN',
  PHP: 'PHP',
  PLN: 'PLN',
  QAR: 'QAR',
  RON: 'RON',
  RUB: 'RUB',
  RWF: 'RWF',
  WST: 'WST',
  SAR: 'SAR',
  RSD: 'RSD',
  SCR: 'SCR',
  SGD: 'SGD',
  SDG: 'SDG',
  SYP: 'SYP',
  ZAR: 'ZAR',
  KRW: 'KRW',
  SSP: 'SSP',
  SBD: 'SBD',
  LKR: 'LKR',
  SRD: 'SRD',
  SZL: 'SZL',
  SEK: 'SEK',
  CHF: 'CHF',
  TWD: 'TWD',
  THB: 'THB',
  TZS: 'TZS',
  TTD: 'TTD',
  TND: 'TND',
  TRY: 'TRY',
  TMT: 'TMT',
  UGX: 'UGX',
  UAH: 'UAH',
  AED: 'AED',
  UYU: 'UYU',
  UZS: 'UZS',
  VUV: 'VUV',
  VND: 'VND',
  XOF: 'XOF',
  YER: 'YER',
  ZMW: 'ZMW',
  BYN: 'BYN',
  BYR: 'BYR',
  DJF: 'DJF',
  ERN: 'ERN',
  FKP: 'FKP',
  GIP: 'GIP',
  GNF: 'GNF',
  IRR: 'IRR',
  KID: 'KID',
  LYD: 'LYD',
  MRU: 'MRU',
  SLL: 'SLL',
  SHP: 'SHP',
  SOS: 'SOS',
  STD: 'STD',
  STN: 'STN',
  TJS: 'TJS',
  TOP: 'TOP',
  VED: 'VED',
  VEF: 'VEF',
  VES: 'VES',
  XXX: 'XXX'
}

module.exports.enumCustomerErrorCode = {
  BLANK: 'BLANK',
  INVALID: 'INVALID',
  TAKEN: 'TAKEN',
  TOO_LONG: 'TOO_LONG',
  TOO_SHORT: 'TOO_SHORT',
  UNIDENTIFIED_CUSTOMER: 'UNIDENTIFIED_CUSTOMER',
  CUSTOMER_DISABLED: 'CUSTOMER_DISABLED',
  PASSWORD_STARTS_OR_ENDS_WITH_WHITESPACE: 'PASSWORD_STARTS_OR_ENDS_WITH_WHITESPACE',
  CONTAINS_HTML_TAGS: 'CONTAINS_HTML_TAGS',
  CONTAINS_URL: 'CONTAINS_URL',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ALREADY_ENABLED: 'ALREADY_ENABLED',
  NOT_FOUND: 'NOT_FOUND',
  BAD_DOMAIN: 'BAD_DOMAIN',
  INVALID_MULTIPASS_REQUEST: 'INVALID_MULTIPASS_REQUEST'
}

module.exports.enumDeliveryMethodType = {
  SHIPPING: 'SHIPPING',
  PICK_UP: 'PICK_UP',
  RETAIL: 'RETAIL',
  LOCAL: 'LOCAL',
  PICKUP_POINT: 'PICKUP_POINT',
  NONE: 'NONE'
}

module.exports.enumDigitalWallet = {
  APPLE_PAY: 'APPLE_PAY',
  ANDROID_PAY: 'ANDROID_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  SHOPIFY_PAY: 'SHOPIFY_PAY'
}

module.exports.enumDiscountApplicationAllocationMethod = {
  ACROSS: 'ACROSS',
  EACH: 'EACH',
  ONE: 'ONE'
}

module.exports.enumDiscountApplicationTargetSelection = {
  ALL: 'ALL',
  ENTITLED: 'ENTITLED',
  EXPLICIT: 'EXPLICIT'
}

module.exports.enumDiscountApplicationTargetType = {
  LINE_ITEM: 'LINE_ITEM',
  SHIPPING_LINE: 'SHIPPING_LINE'
}

module.exports.enumFilterType = {
  LIST: 'LIST',
  PRICE_RANGE: 'PRICE_RANGE',
  BOOLEAN: 'BOOLEAN'
}

module.exports.enumImageContentType = {
  PNG: 'PNG',
  JPG: 'JPG',
  WEBP: 'WEBP'
}

module.exports.enumLanguageCode = {
  AF: 'AF',
  AK: 'AK',
  AM: 'AM',
  AR: 'AR',
  AS: 'AS',
  AZ: 'AZ',
  BE: 'BE',
  BG: 'BG',
  BM: 'BM',
  BN: 'BN',
  BO: 'BO',
  BR: 'BR',
  BS: 'BS',
  CA: 'CA',
  CE: 'CE',
  CKB: 'CKB',
  CS: 'CS',
  CY: 'CY',
  DA: 'DA',
  DE: 'DE',
  DZ: 'DZ',
  EE: 'EE',
  EL: 'EL',
  EN: 'EN',
  EO: 'EO',
  ES: 'ES',
  ET: 'ET',
  EU: 'EU',
  FA: 'FA',
  FF: 'FF',
  FI: 'FI',
  FIL: 'FIL',
  FO: 'FO',
  FR: 'FR',
  FY: 'FY',
  GA: 'GA',
  GD: 'GD',
  GL: 'GL',
  GU: 'GU',
  GV: 'GV',
  HA: 'HA',
  HE: 'HE',
  HI: 'HI',
  HR: 'HR',
  HU: 'HU',
  HY: 'HY',
  IA: 'IA',
  ID: 'ID',
  IG: 'IG',
  II: 'II',
  IS: 'IS',
  IT: 'IT',
  JA: 'JA',
  JV: 'JV',
  KA: 'KA',
  KI: 'KI',
  KK: 'KK',
  KL: 'KL',
  KM: 'KM',
  KN: 'KN',
  KO: 'KO',
  KS: 'KS',
  KU: 'KU',
  KW: 'KW',
  KY: 'KY',
  LB: 'LB',
  LG: 'LG',
  LN: 'LN',
  LO: 'LO',
  LT: 'LT',
  LU: 'LU',
  LV: 'LV',
  MG: 'MG',
  MI: 'MI',
  MK: 'MK',
  ML: 'ML',
  MN: 'MN',
  MR: 'MR',
  MS: 'MS',
  MT: 'MT',
  MY: 'MY',
  NB: 'NB',
  ND: 'ND',
  NE: 'NE',
  NL: 'NL',
  NN: 'NN',
  NO: 'NO',
  OM: 'OM',
  OR: 'OR',
  OS: 'OS',
  PA: 'PA',
  PL: 'PL',
  PS: 'PS',
  PT_BR: 'PT_BR',
  PT_PT: 'PT_PT',
  QU: 'QU',
  RM: 'RM',
  RN: 'RN',
  RO: 'RO',
  RU: 'RU',
  RW: 'RW',
  SA: 'SA',
  SC: 'SC',
  SD: 'SD',
  SE: 'SE',
  SG: 'SG',
  SI: 'SI',
  SK: 'SK',
  SL: 'SL',
  SN: 'SN',
  SO: 'SO',
  SQ: 'SQ',
  SR: 'SR',
  SU: 'SU',
  SV: 'SV',
  SW: 'SW',
  TA: 'TA',
  TE: 'TE',
  TG: 'TG',
  TH: 'TH',
  TI: 'TI',
  TK: 'TK',
  TO: 'TO',
  TR: 'TR',
  TT: 'TT',
  UG: 'UG',
  UK: 'UK',
  UR: 'UR',
  UZ: 'UZ',
  VI: 'VI',
  WO: 'WO',
  XH: 'XH',
  YI: 'YI',
  YO: 'YO',
  ZH_CN: 'ZH_CN',
  ZH_TW: 'ZH_TW',
  ZU: 'ZU',
  ZH: 'ZH',
  PT: 'PT',
  CU: 'CU',
  VO: 'VO',
  LA: 'LA',
  SH: 'SH',
  MO: 'MO'
}

module.exports.enumLocationSortKeys = {
  ID: 'ID',
  CITY: 'CITY',
  DISTANCE: 'DISTANCE',
  NAME: 'NAME'
}

module.exports.enumMediaContentType = {
  EXTERNAL_VIDEO: 'EXTERNAL_VIDEO',
  IMAGE: 'IMAGE',
  MODEL_3D: 'MODEL_3D',
  VIDEO: 'VIDEO'
}

module.exports.enumMediaHost = {
  YOUTUBE: 'YOUTUBE',
  VIMEO: 'VIMEO'
}

module.exports.enumMediaPresentationFormat = {
  MODEL_VIEWER: 'MODEL_VIEWER',
  IMAGE: 'IMAGE'
}

module.exports.enumMenuItemType = {
  FRONTPAGE: 'FRONTPAGE',
  COLLECTION: 'COLLECTION',
  COLLECTIONS: 'COLLECTIONS',
  PRODUCT: 'PRODUCT',
  CATALOG: 'CATALOG',
  PAGE: 'PAGE',
  BLOG: 'BLOG',
  ARTICLE: 'ARTICLE',
  SEARCH: 'SEARCH',
  SHOP_POLICY: 'SHOP_POLICY',
  HTTP: 'HTTP'
}

module.exports.enumMetafieldDeleteErrorCode = {
  INVALID_OWNER: 'INVALID_OWNER',
  METAFIELD_DOES_NOT_EXIST: 'METAFIELD_DOES_NOT_EXIST'
}

module.exports.enumMetafieldsSetUserErrorCode = {
  BLANK: 'BLANK',
  INCLUSION: 'INCLUSION',
  LESS_THAN_OR_EQUAL_TO: 'LESS_THAN_OR_EQUAL_TO',
  PRESENT: 'PRESENT',
  TOO_SHORT: 'TOO_SHORT',
  TOO_LONG: 'TOO_LONG',
  INVALID_OWNER: 'INVALID_OWNER',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_TYPE: 'INVALID_TYPE'
}

module.exports.enumOrderCancelReason = {
  CUSTOMER: 'CUSTOMER',
  FRAUD: 'FRAUD',
  INVENTORY: 'INVENTORY',
  DECLINED: 'DECLINED',
  OTHER: 'OTHER'
}

module.exports.enumOrderFinancialStatus = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  VOIDED: 'VOIDED',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED'
}

module.exports.enumOrderFulfillmentStatus = {
  UNFULFILLED: 'UNFULFILLED',
  PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
  FULFILLED: 'FULFILLED',
  RESTOCKED: 'RESTOCKED',
  PENDING_FULFILLMENT: 'PENDING_FULFILLMENT',
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  ON_HOLD: 'ON_HOLD',
  SCHEDULED: 'SCHEDULED'
}

module.exports.enumOrderSortKeys = {
  PROCESSED_AT: 'PROCESSED_AT',
  TOTAL_PRICE: 'TOTAL_PRICE',
  ID: 'ID',
  RELEVANCE: 'RELEVANCE'
}

module.exports.enumPageSortKeys = {
  ID: 'ID',
  UPDATED_AT: 'UPDATED_AT',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE'
}

module.exports.enumPaymentTokenType = {
  APPLE_PAY: 'APPLE_PAY',
  VAULT: 'VAULT',
  SHOPIFY_PAY: 'SHOPIFY_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  STRIPE_VAULT_TOKEN: 'STRIPE_VAULT_TOKEN'
}

module.exports.enumPredictiveSearchLimitScope = {
  ALL: 'ALL',
  EACH: 'EACH'
}

module.exports.enumPredictiveSearchType = {
  COLLECTION: 'COLLECTION',
  PRODUCT: 'PRODUCT',
  PAGE: 'PAGE',
  ARTICLE: 'ARTICLE',
  QUERY: 'QUERY'
}

module.exports.enumProductCollectionSortKeys = {
  BEST_SELLING: 'BEST_SELLING',
  CREATED: 'CREATED',
  COLLECTION_DEFAULT: 'COLLECTION_DEFAULT',
  ID: 'ID',
  MANUAL: 'MANUAL',
  PRICE: 'PRICE',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE'
}

module.exports.enumProductImageSortKeys = {
  CREATED_AT: 'CREATED_AT',
  POSITION: 'POSITION',
  ID: 'ID',
  RELEVANCE: 'RELEVANCE'
}

module.exports.enumProductMediaSortKeys = {
  POSITION: 'POSITION',
  ID: 'ID',
  RELEVANCE: 'RELEVANCE'
}

module.exports.enumProductRecommendationIntent = {
  RELATED: 'RELATED',
  COMPLEMENTARY: 'COMPLEMENTARY'
}

module.exports.enumProductSortKeys = {
  BEST_SELLING: 'BEST_SELLING',
  CREATED_AT: 'CREATED_AT',
  ID: 'ID',
  PRICE: 'PRICE',
  PRODUCT_TYPE: 'PRODUCT_TYPE',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE',
  UPDATED_AT: 'UPDATED_AT',
  VENDOR: 'VENDOR'
}

module.exports.enumProductVariantSortKeys = {
  ID: 'ID',
  POSITION: 'POSITION',
  RELEVANCE: 'RELEVANCE',
  TITLE: 'TITLE',
  SKU: 'SKU'
}

module.exports.enumSearchPrefixQueryType = {
  LAST: 'LAST',
  NONE: 'NONE'
}

module.exports.enumSearchSortKeys = {
  PRICE: 'PRICE',
  RELEVANCE: 'RELEVANCE'
}

module.exports.enumSearchType = {
  PRODUCT: 'PRODUCT',
  PAGE: 'PAGE',
  ARTICLE: 'ARTICLE'
}

module.exports.enumSearchUnavailableProductsType = {
  SHOW: 'SHOW',
  HIDE: 'HIDE',
  LAST: 'LAST'
}

module.exports.enumSearchableField = {
  AUTHOR: 'AUTHOR',
  BODY: 'BODY',
  PRODUCT_TYPE: 'PRODUCT_TYPE',
  TAG: 'TAG',
  TITLE: 'TITLE',
  VARIANTS_BARCODE: 'VARIANTS_BARCODE',
  VARIANTS_SKU: 'VARIANTS_SKU',
  VARIANTS_TITLE: 'VARIANTS_TITLE',
  VENDOR: 'VENDOR'
}

module.exports.enumSellingPlanCheckoutChargeType = {
  PERCENTAGE: 'PERCENTAGE',
  PRICE: 'PRICE'
}

module.exports.enumSubmissionErrorCode = {
  ERROR: 'ERROR',
  NO_DELIVERY_GROUP_SELECTED: 'NO_DELIVERY_GROUP_SELECTED',
  BUYER_IDENTITY_EMAIL_IS_INVALID: 'BUYER_IDENTITY_EMAIL_IS_INVALID',
  BUYER_IDENTITY_EMAIL_REQUIRED: 'BUYER_IDENTITY_EMAIL_REQUIRED',
  BUYER_IDENTITY_PHONE_IS_INVALID: 'BUYER_IDENTITY_PHONE_IS_INVALID',
  DELIVERY_ADDRESS1_INVALID: 'DELIVERY_ADDRESS1_INVALID',
  DELIVERY_ADDRESS1_REQUIRED: 'DELIVERY_ADDRESS1_REQUIRED',
  DELIVERY_ADDRESS1_TOO_LONG: 'DELIVERY_ADDRESS1_TOO_LONG',
  DELIVERY_ADDRESS2_INVALID: 'DELIVERY_ADDRESS2_INVALID',
  DELIVERY_ADDRESS2_REQUIRED: 'DELIVERY_ADDRESS2_REQUIRED',
  DELIVERY_ADDRESS2_TOO_LONG: 'DELIVERY_ADDRESS2_TOO_LONG',
  DELIVERY_CITY_INVALID: 'DELIVERY_CITY_INVALID',
  DELIVERY_CITY_REQUIRED: 'DELIVERY_CITY_REQUIRED',
  DELIVERY_CITY_TOO_LONG: 'DELIVERY_CITY_TOO_LONG',
  DELIVERY_COMPANY_INVALID: 'DELIVERY_COMPANY_INVALID',
  DELIVERY_COMPANY_REQUIRED: 'DELIVERY_COMPANY_REQUIRED',
  DELIVERY_COMPANY_TOO_LONG: 'DELIVERY_COMPANY_TOO_LONG',
  DELIVERY_COUNTRY_REQUIRED: 'DELIVERY_COUNTRY_REQUIRED',
  DELIVERY_FIRST_NAME_INVALID: 'DELIVERY_FIRST_NAME_INVALID',
  DELIVERY_FIRST_NAME_REQUIRED: 'DELIVERY_FIRST_NAME_REQUIRED',
  DELIVERY_FIRST_NAME_TOO_LONG: 'DELIVERY_FIRST_NAME_TOO_LONG',
  DELIVERY_INVALID_POSTAL_CODE_FOR_COUNTRY: 'DELIVERY_INVALID_POSTAL_CODE_FOR_COUNTRY',
  DELIVERY_INVALID_POSTAL_CODE_FOR_ZONE: 'DELIVERY_INVALID_POSTAL_CODE_FOR_ZONE',
  DELIVERY_LAST_NAME_INVALID: 'DELIVERY_LAST_NAME_INVALID',
  DELIVERY_LAST_NAME_REQUIRED: 'DELIVERY_LAST_NAME_REQUIRED',
  DELIVERY_LAST_NAME_TOO_LONG: 'DELIVERY_LAST_NAME_TOO_LONG',
  DELIVERY_NO_DELIVERY_AVAILABLE: 'DELIVERY_NO_DELIVERY_AVAILABLE',
  DELIVERY_NO_DELIVERY_AVAILABLE_FOR_MERCHANDISE_LINE: 'DELIVERY_NO_DELIVERY_AVAILABLE_FOR_MERCHANDISE_LINE',
  DELIVERY_OPTIONS_PHONE_NUMBER_INVALID: 'DELIVERY_OPTIONS_PHONE_NUMBER_INVALID',
  DELIVERY_OPTIONS_PHONE_NUMBER_REQUIRED: 'DELIVERY_OPTIONS_PHONE_NUMBER_REQUIRED',
  DELIVERY_PHONE_NUMBER_INVALID: 'DELIVERY_PHONE_NUMBER_INVALID',
  DELIVERY_PHONE_NUMBER_REQUIRED: 'DELIVERY_PHONE_NUMBER_REQUIRED',
  DELIVERY_POSTAL_CODE_INVALID: 'DELIVERY_POSTAL_CODE_INVALID',
  DELIVERY_POSTAL_CODE_REQUIRED: 'DELIVERY_POSTAL_CODE_REQUIRED',
  DELIVERY_ZONE_NOT_FOUND: 'DELIVERY_ZONE_NOT_FOUND',
  DELIVERY_ZONE_REQUIRED_FOR_COUNTRY: 'DELIVERY_ZONE_REQUIRED_FOR_COUNTRY',
  DELIVERY_ADDRESS_REQUIRED: 'DELIVERY_ADDRESS_REQUIRED',
  MERCHANDISE_NOT_APPLICABLE: 'MERCHANDISE_NOT_APPLICABLE',
  MERCHANDISE_LINE_LIMIT_REACHED: 'MERCHANDISE_LINE_LIMIT_REACHED',
  MERCHANDISE_NOT_ENOUGH_STOCK_AVAILABLE: 'MERCHANDISE_NOT_ENOUGH_STOCK_AVAILABLE',
  MERCHANDISE_OUT_OF_STOCK: 'MERCHANDISE_OUT_OF_STOCK',
  MERCHANDISE_PRODUCT_NOT_PUBLISHED: 'MERCHANDISE_PRODUCT_NOT_PUBLISHED',
  PAYMENTS_ADDRESS1_INVALID: 'PAYMENTS_ADDRESS1_INVALID',
  PAYMENTS_ADDRESS1_REQUIRED: 'PAYMENTS_ADDRESS1_REQUIRED',
  PAYMENTS_ADDRESS1_TOO_LONG: 'PAYMENTS_ADDRESS1_TOO_LONG',
  PAYMENTS_ADDRESS2_INVALID: 'PAYMENTS_ADDRESS2_INVALID',
  PAYMENTS_ADDRESS2_REQUIRED: 'PAYMENTS_ADDRESS2_REQUIRED',
  PAYMENTS_ADDRESS2_TOO_LONG: 'PAYMENTS_ADDRESS2_TOO_LONG',
  PAYMENTS_CITY_INVALID: 'PAYMENTS_CITY_INVALID',
  PAYMENTS_CITY_REQUIRED: 'PAYMENTS_CITY_REQUIRED',
  PAYMENTS_CITY_TOO_LONG: 'PAYMENTS_CITY_TOO_LONG',
  PAYMENTS_COMPANY_INVALID: 'PAYMENTS_COMPANY_INVALID',
  PAYMENTS_COMPANY_REQUIRED: 'PAYMENTS_COMPANY_REQUIRED',
  PAYMENTS_COMPANY_TOO_LONG: 'PAYMENTS_COMPANY_TOO_LONG',
  PAYMENTS_COUNTRY_REQUIRED: 'PAYMENTS_COUNTRY_REQUIRED',
  PAYMENTS_CREDIT_CARD_BASE_EXPIRED: 'PAYMENTS_CREDIT_CARD_BASE_EXPIRED',
  PAYMENTS_CREDIT_CARD_BASE_GATEWAY_NOT_SUPPORTED: 'PAYMENTS_CREDIT_CARD_BASE_GATEWAY_NOT_SUPPORTED',
  PAYMENTS_CREDIT_CARD_BASE_INVALID_START_DATE_OR_ISSUE_NUMBER_FOR_DEBIT: 'PAYMENTS_CREDIT_CARD_BASE_INVALID_START_DATE_OR_ISSUE_NUMBER_FOR_DEBIT',
  PAYMENTS_CREDIT_CARD_BRAND_NOT_SUPPORTED: 'PAYMENTS_CREDIT_CARD_BRAND_NOT_SUPPORTED',
  PAYMENTS_CREDIT_CARD_FIRST_NAME_BLANK: 'PAYMENTS_CREDIT_CARD_FIRST_NAME_BLANK',
  PAYMENTS_CREDIT_CARD_GENERIC: 'PAYMENTS_CREDIT_CARD_GENERIC',
  PAYMENTS_CREDIT_CARD_LAST_NAME_BLANK: 'PAYMENTS_CREDIT_CARD_LAST_NAME_BLANK',
  PAYMENTS_CREDIT_CARD_MONTH_INCLUSION: 'PAYMENTS_CREDIT_CARD_MONTH_INCLUSION',
  PAYMENTS_CREDIT_CARD_NAME_INVALID: 'PAYMENTS_CREDIT_CARD_NAME_INVALID',
  PAYMENTS_CREDIT_CARD_NUMBER_INVALID: 'PAYMENTS_CREDIT_CARD_NUMBER_INVALID',
  PAYMENTS_CREDIT_CARD_NUMBER_INVALID_FORMAT: 'PAYMENTS_CREDIT_CARD_NUMBER_INVALID_FORMAT',
  PAYMENTS_CREDIT_CARD_SESSION_ID: 'PAYMENTS_CREDIT_CARD_SESSION_ID',
  PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_BLANK: 'PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_BLANK',
  PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_INVALID_FOR_CARD_TYPE: 'PAYMENTS_CREDIT_CARD_VERIFICATION_VALUE_INVALID_FOR_CARD_TYPE',
  PAYMENTS_CREDIT_CARD_YEAR_EXPIRED: 'PAYMENTS_CREDIT_CARD_YEAR_EXPIRED',
  PAYMENTS_CREDIT_CARD_YEAR_INVALID_EXPIRY_YEAR: 'PAYMENTS_CREDIT_CARD_YEAR_INVALID_EXPIRY_YEAR',
  PAYMENTS_FIRST_NAME_INVALID: 'PAYMENTS_FIRST_NAME_INVALID',
  PAYMENTS_FIRST_NAME_REQUIRED: 'PAYMENTS_FIRST_NAME_REQUIRED',
  PAYMENTS_FIRST_NAME_TOO_LONG: 'PAYMENTS_FIRST_NAME_TOO_LONG',
  PAYMENTS_INVALID_POSTAL_CODE_FOR_COUNTRY: 'PAYMENTS_INVALID_POSTAL_CODE_FOR_COUNTRY',
  PAYMENTS_INVALID_POSTAL_CODE_FOR_ZONE: 'PAYMENTS_INVALID_POSTAL_CODE_FOR_ZONE',
  PAYMENTS_LAST_NAME_INVALID: 'PAYMENTS_LAST_NAME_INVALID',
  PAYMENTS_LAST_NAME_REQUIRED: 'PAYMENTS_LAST_NAME_REQUIRED',
  PAYMENTS_LAST_NAME_TOO_LONG: 'PAYMENTS_LAST_NAME_TOO_LONG',
  PAYMENTS_METHOD_UNAVAILABLE: 'PAYMENTS_METHOD_UNAVAILABLE',
  PAYMENTS_METHOD_REQUIRED: 'PAYMENTS_METHOD_REQUIRED',
  PAYMENTS_UNACCEPTABLE_PAYMENT_AMOUNT: 'PAYMENTS_UNACCEPTABLE_PAYMENT_AMOUNT',
  PAYMENTS_PHONE_NUMBER_INVALID: 'PAYMENTS_PHONE_NUMBER_INVALID',
  PAYMENTS_PHONE_NUMBER_REQUIRED: 'PAYMENTS_PHONE_NUMBER_REQUIRED',
  PAYMENTS_POSTAL_CODE_INVALID: 'PAYMENTS_POSTAL_CODE_INVALID',
  PAYMENTS_POSTAL_CODE_REQUIRED: 'PAYMENTS_POSTAL_CODE_REQUIRED',
  PAYMENTS_SHOPIFY_PAYMENTS_REQUIRED: 'PAYMENTS_SHOPIFY_PAYMENTS_REQUIRED',
  PAYMENTS_WALLET_CONTENT_MISSING: 'PAYMENTS_WALLET_CONTENT_MISSING',
  PAYMENTS_BILLING_ADDRESS_ZONE_NOT_FOUND: 'PAYMENTS_BILLING_ADDRESS_ZONE_NOT_FOUND',
  PAYMENTS_BILLING_ADDRESS_ZONE_REQUIRED_FOR_COUNTRY: 'PAYMENTS_BILLING_ADDRESS_ZONE_REQUIRED_FOR_COUNTRY',
  TAXES_MUST_BE_DEFINED: 'TAXES_MUST_BE_DEFINED',
  TAXES_LINE_ID_NOT_FOUND: 'TAXES_LINE_ID_NOT_FOUND',
  TAXES_DELIVERY_GROUP_ID_NOT_FOUND: 'TAXES_DELIVERY_GROUP_ID_NOT_FOUND'
}

module.exports.enumTransactionKind = {
  SALE: 'SALE',
  CAPTURE: 'CAPTURE',
  AUTHORIZATION: 'AUTHORIZATION',
  EMV_AUTHORIZATION: 'EMV_AUTHORIZATION',
  CHANGE: 'CHANGE'
}

module.exports.enumTransactionStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  ERROR: 'ERROR'
}

module.exports.enumUnitPriceMeasurementMeasuredType = {
  VOLUME: 'VOLUME',
  WEIGHT: 'WEIGHT',
  LENGTH: 'LENGTH',
  AREA: 'AREA'
}

module.exports.enumUnitPriceMeasurementMeasuredUnit = {
  ML: 'ML',
  CL: 'CL',
  L: 'L',
  M3: 'M3',
  MG: 'MG',
  G: 'G',
  KG: 'KG',
  MM: 'MM',
  CM: 'CM',
  M: 'M',
  M2: 'M2'
}

module.exports.enumUnitSystem = {
  IMPERIAL_SYSTEM: 'IMPERIAL_SYSTEM',
  METRIC_SYSTEM: 'METRIC_SYSTEM'
}

module.exports.enumWeightUnit = {
  KILOGRAMS: 'KILOGRAMS',
  GRAMS: 'GRAMS',
  POUNDS: 'POUNDS',
  OUNCES: 'OUNCES'
}


  module.exports.generateQueryOp = function(fields) {
    return generateGraphqlOperation('query', typeMap.Query, fields)
  }
  module.exports.generateMutationOp = function(fields) {
    return generateGraphqlOperation('mutation', typeMap.Mutation, fields)
  }
  module.exports.generateSubscriptionOp = function(fields) {
    return generateGraphqlOperation('subscription', typeMap.Subscription, fields)
  }
  module.exports.everything = {
    __scalar: true
  }

  var schemaExports = require('./guards.cjs')
  for (var k in schemaExports) {
    module.exports[k] = schemaExports[k];
  }
  